import * as fs from "fs";
import * as path from "path";
import * as vscode from "vscode";
import { baseFiles, RdkConfig } from "./config";

/**
 * Render the compose overlay.
 *
 * This mirrors `_render_overlay` in bin/rdk and must stay in step with it: the extension and
 * the CLI have to produce the same deployment from the same .env.remote, or you get different
 * results depending on which one you happened to use.
 *
 * Compose forbids variable interpolation in service KEYS (`${APP_SERVICE}:` is rejected), so
 * this cannot be a static file shipped in stacks/ — the real service name has to be baked in.
 */
export function renderOverlay(ctx: vscode.ExtensionContext, cfg: RdkConfig, root: string): string {
  const net = cfg.proxyNetwork || "coolify";
  const router = `${cfg.projectName}-web`;
  const httpRouter = `${cfg.projectName}-http`;
  const redirect = `${cfg.projectName}-redirect`;

  const lines = [
    "# Generated by the Remote Dev Kit extension — do not edit.",
    "# Your compose file stays the source of truth.",
    "networks:",
    "  proxy:",
    "    external: true",
    `    name: ${net}`,
    "",
    "services:",
    `  ${cfg.appService}:`,
    "    networks: [default, proxy]",
    "    labels:",
    "      - traefik.enable=true",
    `      - traefik.docker.network=${net}`,
    `      - traefik.http.routers.${router}.rule=Host(\`${cfg.appHost}\`)`,
    `      - traefik.http.routers.${router}.entrypoints=${cfg.certEntrypoint}`,
    `      - traefik.http.routers.${router}.tls=true`,
    `      - traefik.http.routers.${router}.tls.certresolver=${cfg.certResolver}`,
    `      - traefik.http.services.${router}.loadbalancer.server.port=${cfg.appPort}`,
    // Plain-HTTP router that only redirects — Coolify's Traefik has no global
    // http→https redirect, so without this port 80 404s.
    `      - traefik.http.routers.${httpRouter}.rule=Host(\`${cfg.appHost}\`)`,
    `      - traefik.http.routers.${httpRouter}.entrypoints=${cfg.httpEntrypoint}`,
    `      - traefik.http.routers.${httpRouter}.middlewares=${redirect}`,
    `      - traefik.http.middlewares.${redirect}.redirectscheme.scheme=https`,
    `      - traefik.http.middlewares.${redirect}.redirectscheme.permanent=true`,
  ];

  // Only add hot-reload sync if the author hasn't written their own: compose appends sequences
  // on merge, so a duplicate `develop.watch` would double every sync rule.
  if (!baseHasDevelop(root, cfg)) {
    lines.push(
      "    develop:",
      "      watch:",
      "        - action: sync",
      "          path: .",
      "          target: /app",
      "          ignore: [.git/, .venv/, node_modules/, __pycache__/, '*.pyc']",
    );
  }

  const dir = path.join(ctx.globalStorageUri.fsPath, "overlay", cfg.projectName);
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, "overlay.yml");
  fs.writeFileSync(file, lines.join("\n") + "\n", "utf8");
  return file;
}

function baseHasDevelop(root: string, cfg: RdkConfig): boolean {
  const first = baseFiles(cfg)[0];
  if (!first) return false;
  try {
    return /^\s+develop:/m.test(fs.readFileSync(path.join(root, first), "utf8"));
  } catch {
    return false;
  }
}
